<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <!-- Import tModLoader mod properties -->
  <Import Project="..\tModLoader.targets" />

  <!-- General -->
  <PropertyGroup>
    <AssemblyName>MarvelMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tools\**" />
    <None Remove="tools\**" />
  </ItemGroup>

</Project>
