namespace MarvelMod.Common.Suits
{
	// One selectable armour piece: a name and a small pixel mask.
	// Mask characters (see SuitRenderer.RoleOf):
	//   .  leave the pixel as it is        X  erase the pixel
	//   P  primary colour                  S  secondary colour
	//   A  accent colour                   T  trim colour
	//   J  undersuit colour                O  dark seam
	//   E  eye glow   R  reactor glow   H  repulsor glow   F  thruster glow
	public class SuitPart
	{
		public string Name { get; }
		public string[] Mask { get; }

		public SuitPart(string name, params string[] mask) {
			Name = name;
			Mask = mask;
		}
	}

	// Every armour piece the Suit Workshop offers. The layout of the 27 x 27 suit canvas (x right, y down, feet on row 26):
	//   helmet 9x9 at (8,0)      faceplate 7x4 at (9,5)    eyes 7x2 at (9,5)
	//   chest 11x8 at (7,9)      reactor 5x3 at (10,11)    emblem 5x3 at (10,14)
	//   shoulder 4x4 at (4,9)    gauntlet 4x5 at (4,14)    (both mirrored onto the right side)
	//   belt 9x2 at (8,16)       legs 9x6 at (8,18)        boots 11x3 at (7,24)
	// Back modules are drawn in code (SuitRenderer.DrawBack) because they're mostly empty space.
	public static class SuitParts
	{
		public static readonly SuitPart[] Helmets = {
			new("Classic",
				".........",
				".........",
				"..PPPPP..",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Mark I Bucket",
				".........",
				"..TTTTT..",
				".PPPPPPP.",
				".PTPPPTP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP."),
			new("Rounded",
				".........",
				"...PPP...",
				"..PPPPP..",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP..",
				"...PPP..."),
			new("Angular",
				".........",
				".........",
				".PPPPPPP.",
				"PPPPPPPPP",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP..",
				"...PPP..."),
			new("Crested",
				"....A....",
				"...AAA...",
				"..PPAPP..",
				".PPPAPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Horned",
				"A.......A",
				".A.....A.",
				".APPPPPA.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Tall Crest",
				"...AAA...",
				"...AAA...",
				"..PAAAP..",
				".PPPAPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Bulky",
				".........",
				".PPPPPPP.",
				"PPPPPPPPP",
				"PPPPPPPPP",
				"PPPPPPPPP",
				"PPPPPPPPP",
				"PPPPPPPPP",
				"PPPPPPPPP",
				".PPPPPPP."),
			new("Sleek",
				".........",
				".........",
				"...PPP...",
				"..PPPPP..",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP..",
				"...PPP..."),
			new("Visor Dome",
				".........",
				"..TTTTT..",
				".TPPPPPT.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Spiked",
				"..A.A.A..",
				"..A.A.A..",
				"..PPPPP..",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Winged",
				".........",
				"A.......A",
				"AAPPPPPAA",
				".APPPPPA.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Knight",
				"....T....",
				"...TTT...",
				"..PPTPP..",
				".PPPTPPP.",
				".PPPTPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Samurai",
				"A.......A",
				".A..A..A.",
				"..AAAAA..",
				"SPPPPPPPS",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
			new("Stealth",
				".........",
				".........",
				"..PPPPP..",
				".PPPPPPP.",
				"PPPPPPPPP",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP..",
				"...PPP..."),
			new("Prototype",
				"......A..",
				"......A..",
				"..PPPPPA.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				".PPPPPPP.",
				"..PPPPP.."),
		};

		public static readonly SuitPart[] Faceplates = {
			new("Classic Mask",
				".SSSSS.",
				".SSSSS.",
				".SSSSS.",
				"..SSS.."),
			new("Open Jaw",
				".SSSSS.",
				".SSSSS.",
				".JJJJJ.",
				"..JJJ.."),
			new("Grill",
				".SSSSS.",
				".SSSSS.",
				".SOSOS.",
				"..SOS.."),
			new("Full Visor",
				"SSSSSSS",
				"SSSSSSS",
				"SSSSSSS",
				".SSSSS."),
			new("Split",
				".SSTSS.",
				".SSTSS.",
				".SSTSS.",
				"..STS.."),
			new("Skull",
				".SSSSS.",
				".SSSSS.",
				"..SOS..",
				"..OSO.."),
			new("Smooth",
				".......",
				".......",
				".......",
				"......."),
			new("Vent Cheeks",
				".SSSSS.",
				"TSSSSST",
				"TSSSSST",
				"..SSS.."),
			new("Mouthless",
				".SSSSS.",
				".SSSSS.",
				".......",
				"......."),
			new("Tech Lines",
				".SSSSS.",
				".SASAS.",
				".SSSSS.",
				"..SAS.."),
		};

		public static readonly SuitPart[] Eyes = {
			new("Classic Slits", ".......", ".EE.EE."),
			new("Wide Slits", ".......", "EEE.EEE"),
			new("Narrow", ".......", "..E.E.."),
			new("Angry", ".E...E.", ".EE.EE."),
			new("Round", ".EE.EE.", ".EE.EE."),
			new("Visor Bar", ".......", ".EEEEE."),
			new("Single Band", ".......", "EEEEEEE"),
			new("T-Visor", ".EEEEE.", "...E..."),
			new("Triple", ".......", ".E.E.E."),
			new("Dots", ".......", ".E...E."),
			new("Goggles", ".EEEEE.", ".EEEEE."),
			new("Tear", ".EE.EE.", "..E.E.."),
		};

		public static readonly SuitPart[] Chests = {
			new("Classic",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"PPPSSSSSPPP",
				"PPPSSSSSPPP",
				"PPPSSSSSPPP",
				".PPPPPPPPP.",
				".PPSSSSSPP.",
				"..PPPPPPP.."),
			new("Mark I Plated",
				".PPPPPPPPP.",
				"PTPPPPPPPTP",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				"PTPPPPPPPTP",
				".PPPPPPPPP.",
				".PPTPPPTPP.",
				"..PPPPPPP.."),
			new("Gold Core",
				".PPPPPPPPP.",
				"PPSSSSSSSPP",
				"PSSSSSSSSSP",
				"PSSSSSSSSSP",
				"PPSSSSSSSPP",
				".PPSSSSSPP.",
				".PPPSSSPPP.",
				"..PPPPPPP.."),
			new("Abs Plates",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				".PPSSOSSPP.",
				".PPSSOSSPP.",
				"..PPPPPPP.."),
			new("V-Stripe",
				".SPPPPPPPS.",
				"PSSPPPPPSSP",
				"PPSSPPPSSPP",
				"PPPSSPSSPPP",
				"PPPPSSSPPPP",
				".PPPPSPPPP.",
				".PPPPPPPPP.",
				"..PPPPPPP.."),
			new("Chevron",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"PAPPPPPPPAP",
				"PPAPPPPPAPP",
				"PPPAPPPAPPP",
				".PPPAPAPPP.",
				".PPPPAPPPP.",
				"..PPPPPPP.."),
			new("Split",
				".PPPPPSSSS.",
				"PPPPPPSSSSS",
				"PPPPPPSSSSS",
				"PPPPPPSSSSS",
				"PPPPPPSSSSS",
				".PPPPPSSSS.",
				".PPPPPSSSS.",
				"..PPPPSSS.."),
			new("Trimmed",
				".TTTTTTTTT.",
				"TPPPPPPPPPT",
				"TPPPPPPPPPT",
				"TPPPPPPPPPT",
				"TPPPPPPPPPT",
				".TPPPPPPPT.",
				".TPPPPPPPT.",
				"..TTTTTTT.."),
			new("Heavy",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				"PPPOPPPOPPP",
				"PPPOPPPOPPP",
				"PPPPPPPPPPP",
				"POOPPPPPOOP",
				".PPPPPPPPP.",
				"..PPPPPPP.."),
			new("Sleek",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				".PPPPPPPPP.",
				".PPPPPPPPP.",
				"..PPPPPPP..",
				"..PPSSSPP..",
				"..PPPPPPP.."),
			new("Racing",
				".PPPPAPPPP.",
				"PPPPPAPPPPP",
				"PPPPPAPPPPP",
				"PPPPPAPPPPP",
				"PPPPPAPPPPP",
				".PPPPAPPPP.",
				".PPPPAPPPP.",
				"..PPPAPPP.."),
			new("Exposed Undersuit",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"PPPPPPPPPPP",
				"PJPJPPPJPJP",
				"PJPJPPPJPJP",
				".JPJJJJJPJ.",
				".PPJJJJJPP.",
				"..PPPPPPP.."),
			new("Ribbed",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"TTTPPPPPTTT",
				"PPPPPPPPPPP",
				"TTTPPPPPTTT",
				".PPPPPPPPP.",
				".TTTTTTTTT.",
				"..PPPPPPP.."),
			new("Sash",
				".SSPPPPPPP.",
				"PPSSPPPPPPP",
				"PPPSSPPPPPP",
				"PPPPSSPPPPP",
				"PPPPPSSPPPP",
				".PPPPPSSPP.",
				".PPPPPPSSP.",
				"..PPPPPPSS."),
			new("Hex Core",
				".PPPPPPPPP.",
				"PPAAAAAAAPP",
				"PPAPPPPPAPP",
				"PPAPPPPPAPP",
				"PPAPPPPPAPP",
				".PAAAAAAAP.",
				".PPPPPPPPP.",
				"..PPPPPPP.."),
			new("Stealth Plates",
				".PPPPPPPPP.",
				"PPPPPPPPPPP",
				"POPPPPPPPOP",
				"PPOPPPPPOPP",
				"PPPOPPPOPPP",
				".PPPOPOPPP.",
				".PPPPOPPPP.",
				"..PPPPPPP.."),
		};

		public static readonly SuitPart[] Reactors = {
			new("Classic", ".TRT.", "TRRRT", ".TRT."),
			new("Triangle", "..R..", ".RRR.", "RRRRR"),
			new("Square", ".RRR.", ".RRR.", ".RRR."),
			new("Hexagon", ".RRR.", "RRRRR", ".RRR."),
			new("Diamond", "..R..", ".RRR.", "..R.."),
			new("Star", "..R..", "RRRRR", ".R.R."),
			new("Ring", ".RRR.", "ROOOR", ".RRR."),
			new("Twin Cells", "RR.RR", "RR.RR", "....."),
			new("Cross", "..R..", "RRRRR", "..R.."),
			new("Mini", ".TTT.", ".TRT.", ".TTT."),
		};

		// Left shoulder; the right one is mirrored.
		public static readonly SuitPart[] Shoulders = {
			new("Classic", ".PPP", "PPPP", "PPPP", ".PP."),
			new("Rounded", "..PP", ".PPP", "PPPP", "PPP."),
			new("Pauldron", "SSSS", "SSSS", "PSSP", ".PP."),
			new("Spiked", "A.PP", ".APP", "PPPP", ".PP."),
			new("Layered", ".SSS", "PPPP", "SSSS", ".PP."),
			new("Slim", "..PP", "..PP", ".PPP", ".PP."),
			new("Heavy", "PPPP", "PPPP", "PPPP", "PPPP"),
			new("Trimmed", ".TTT", "TPPP", "TPPP", ".TT."),
			new("Missile Pod", "SSSP", "SOSP", "SSSP", ".PP."),
			new("Vented", ".PPP", "POPO", "PPPP", ".PP."),
		};

		// Left gauntlet; the right one is mirrored.
		public static readonly SuitPart[] Gauntlets = {
			new("Classic", ".SS.", ".SS.", ".PP.", ".SS.", ".SS."),
			new("Bracer", ".TT.", ".SS.", ".SS.", ".PP.", ".PP."),
			new("Heavy", "SSSS", "SSSS", ".SS.", ".PP.", ".PP."),
			new("Bladed", "A...", "ASS.", ".SS.", ".PP.", ".PP."),
			new("Flared", "PPPP", ".PP.", ".PP.", ".SS.", ".SS."),
			new("Repulsor Glow", ".SS.", ".SS.", ".SS.", ".PP.", ".HH."),
			new("Plain", ".PP.", ".PP.", ".PP.", ".PP.", ".PP."),
			new("Knuckle Guard", ".PP.", ".PP.", ".PP.", "TSS.", ".SS."),
			new("Striped", ".AA.", ".SS.", ".AA.", ".SS.", ".PP."),
			new("Wrist Cannon", ".OO.", "SSSS", ".SS.", ".SS.", ".PP."),
			new("Shielded", "SS..", "SSS.", "SSS.", ".PP.", ".PP."),
			new("Claws", ".SS.", ".SS.", ".SS.", ".PP.", "A.A."),
		};

		public static readonly SuitPart[] Belts = {
			new("Classic", "TTTTTTTTT", "PPPPPPPPP"),
			new("Buckle", "TTTTSTTTT", "PPPPSPPPP"),
			new("Gold", "SSSSSSSSS", "PPPPPPPPP"),
			new("Utility", "TTTTTTTTT", "SPSPPPSPS"),
			new("Undersuit", "JJJJJJJJJ", "PPPPPPPPP"),
			new("Glow Line", "TTTTTTTTT", "PPPPRPPPP"),
			new("Two-Tone", "PPPPPPPPP", "SSSSSSSSS"),
			new("None", ".........", "........."),
		};

		// Columns 0-3 are the left leg, column 4 the crotch, columns 5-8 the right leg.
		public static readonly SuitPart[] Legs = {
			new("Classic", "PPPPPPPPP", "PPPP.PPPP", "PPPP.PPPP", "PSSP.PSSP", "PPPP.PPPP", "PPPP.PPPP"),
			new("Plain", "PPPPPPPPP", "PPPP.PPPP", "PPPP.PPPP", "PPPP.PPPP", "PPPP.PPPP", "PPPP.PPPP"),
			new("Outer Stripe", "PPPPPPPPP", "APPP.PPPA", "APPP.PPPA", "APPP.PPPA", "APPP.PPPA", "APPP.PPPA"),
			new("Thigh Plates", "SSSSPSSSS", "SSSS.SSSS", "PPPP.PPPP", "PPPP.PPPP", "PPPP.PPPP", "PPPP.PPPP"),
			new("Slim", ".PPPPPPP.", ".PPP.PPP.", ".PPP.PPP.", ".PPP.PPP.", ".PPP.PPP.", ".PPP.PPP."),
			new("Armoured", "PPPPPPPPP", "PTTP.PTTP", "PPPP.PPPP", "PPPP.PPPP", "PTTP.PTTP", "PPPP.PPPP"),
			new("Exposed Undersuit", "PPPPPPPPP", "PJJP.PJJP", "PJJP.PJJP", "PPPP.PPPP", "PJJP.PJJP", "PPPP.PPPP"),
			new("Two-Tone", "PPPPPPPPP", "PPPP.PPPP", "PPPP.PPPP", "SSSS.SSSS", "SSSS.SSSS", "SSSS.SSSS"),
			new("Inner Stripe", "PPPPAPPPP", "PPPA.APPP", "PPPA.APPP", "PPPA.APPP", "PPPA.APPP", "PPPA.APPP"),
			new("Heavy", "PPPPPPPPP", "PPPPOPPPP", "PPPPOPPPP", "PPPPOPPPP", "PPPPOPPPP", "PPPPOPPPP"),
			new("Hydraulic", "PPPPPPPPP", "TPPP.PPPT", "TPPP.PPPT", "TSSP.PSST", "TPPP.PPPT", "TPPP.PPPT"),
			new("Racing", "PPPPPPPPP", "SSPP.PPSS", "SSPP.PPSS", "SSPP.PPSS", "SSPP.PPSS", "SSPP.PPSS"),
		};

		// Columns 0-4 are the left boot, column 5 the gap, columns 6-10 the right boot.
		public static readonly SuitPart[] Boots = {
			new("Classic", ".SSSS.SSSS.", ".SSSS.SSSS.", "SSSSS.SSSSS"),
			new("Plain", ".PPPP.PPPP.", ".PPPP.PPPP.", "PPPPP.PPPPP"),
			new("Heavy", "SSSSS.SSSSS", "SSSSS.SSSSS", "OOOOO.OOOOO"),
			new("Thruster", ".SSSS.SSSS.", ".SSSS.SSSS.", ".FFF...FFF."),
			new("Trimmed", ".TTTT.TTTT.", ".SSSS.SSSS.", "SSSSS.SSSSS"),
			new("Pointed", ".SSSS.SSSS.", ".SSSS.SSSS.", "SSSS...SSSS"),
			new("Cuffed", ".AAAA.AAAA.", ".SSSS.SSSS.", "SSSSS.SSSSS"),
			new("Two-Tone", ".PPPP.PPPP.", ".SSSS.SSSS.", "SSSSS.SSSSS"),
			new("Sleek", ".SSSS.SSSS.", ".SSSS.SSSS.", ".SSSS.SSSS."),
			new("Stomper", "PPPPP.PPPPP", "SSSSS.SSSSS", "TTTTT.TTTTT"),
		};

		// 5x3 glyphs; '#' is painted in the emblem colour.
		public static readonly SuitPart[] Emblems = {
			new("None", ".....", ".....", "....."),
			new("Star", "..#..", "#####", ".#.#."),
			new("Triangle", "..#..", ".#.#.", "#####"),
			new("Circle", ".###.", "#...#", ".###."),
			new("Bolt", "...##", ".###.", "##..."),
			new("Wings", "#...#", "##.##", ".###."),
			new("Skull", ".###.", "#.#.#", ".#.#."),
			new("Heart", "##.##", "#####", "..#.."),
			new("Diamond", "..#..", ".###.", "..#.."),
			new("Cross", "..#..", "#####", "..#.."),
			new("Shield", "#####", "#####", ".###."),
			new("Crown", "#.#.#", "#####", "#####"),
		};

		public static readonly string[] BackModules = {
			"None", "Jetpack", "Flight Fins", "Wing Blades", "Twin Tanks",
			"Missile Pods", "Antennae", "Power Pack", "Radiator Fins", "Rocket Boosters"
		};

		public static readonly string[] Patterns = {
			"None", "Racing Stripe", "Twin Stripes", "Chevrons", "Panel Lines", "Hex Plating", "Tiger Stripes",
			"Split Half", "Checker", "Diagonal", "Circuit", "Camo", "Lower Fade", "Dots"
		};

		public static readonly string[] Finishes = { "Metallic", "Matte", "Chrome", "Gloss", "Stealth", "Battle-Damaged" };

		public static string[] Names(SuitPart[] parts) {
			string[] names = new string[parts.Length];
			for (int i = 0; i < parts.Length; i++) {
				names[i] = parts[i].Name;
			}
			return names;
		}
	}
}
